android test

diff --git a/.github/workflows/build-android-50.yml b/.github/workflows/build-android-50.yml
--- a/.github/workflows/build-android-50.yml
+++ b/.github/workflows/build-android-50.yml
@@ -10,6 +10,8 @@ on:
   workflow_dispatch:
 
 jobs:
+  build-ndk-win:
+    uses: ./.github/workflows/build-ndk-win.yml
   build-ndk-android:
     uses: ./.github/workflows/build-ndk-android.yml
   
@@ -43,11 +45,22 @@ jobs:
 
   build-android-50:
     runs-on: [ self-hosted, Windows, X64, w10-1344 ]
-    needs: [ upload-ndk-android ]
+    needs: [ upload-ndk-android, build-ndk-win ]
     steps:
     - uses: actions/checkout@v2
     - name: git-update-dependecies
       run: git submodule update --init --recursive | Write-Host
+    - uses: actions/cache/restore@v3
+      id: ndk-cache-win64
+      with:
+        path: InworldAI\inworld-ndk\build\Package
+        key: ${{ runner.OS }}-ndk-cache-Win64-${{ env.INWORLD_NDK_SHA }}
+    - name: check-cache-success
+      shell: pwsh
+      if: steps.ndk-cache-win64.outputs.cache-hit != 'true'
+      run: |
+        echo "cache restore failed"
+        exit 1
     - uses: actions/download-artifact@v3
       with:
         name: Android-NDK-lib
