test android

diff --git a/.github/workflows/build-android-50.yml b/.github/workflows/build-android-50.yml
--- a/.github/workflows/build-android-50.yml
+++ b/.github/workflows/build-android-50.yml
@@ -32,6 +32,12 @@ jobs:
         key: macOS-ndk-cache-android-${{ env.INWORLD_NDK_SHA }}
         fail-on-cache-miss: true
         enableCrossOsArchive: true
+    - name: Check cache success
+      shell: bash
+      if: steps.ndk-cache-android.outputs.cache-hit != 'true'
+      run: |
+        echo "Cache fail"
+        exit 1
     - name: Copy NDK
       run: |
           $process = Start-Process -FilePath "C:\Program Files\Python310\Python.exe" -Wait -NoNewWindow -PassThru -ArgumentList InworldAI\Source\ThirdParty\Inworld\dev-tools\ndk-util.py,--copy
