multiple fixes

diff --git a/.github/workflows/build-ios-50.yml b/.github/workflows/build-ios-50.yml
--- a/.github/workflows/build-ios-50.yml
+++ b/.github/workflows/build-ios-50.yml
@@ -6,11 +6,6 @@ on:
   workflow_dispatch:
 
 jobs:
-  build-ndk-ios:
-    uses: ./.github/workflows/build-ndk-ios.yml
-  build-ndk-mac:
-    uses: ./.github/workflows/build-ndk-mac.yml
-
   build-ios-50:
     runs-on: [ self-hosted, macOS, ARM64, m1-1317 ]
     needs: [ build-ndk-ios, build-ndk-mac ]
@@ -29,6 +24,11 @@ jobs:
         path: InworldAI/inworld-ndk/build/Package
         key: ${{ runner.OS }}-ndk-cache-iOS-${{ env.INWORLD_NDK_SHA }}
         fail-on-cache-miss: true
+    - name: check-cache-success
+      if: steps.ndk-cache-ios.outputs.cache-hit != 'true'
+      run: |
+        echo "cache restore failed"
+        exit 1
     - uses: actions/cache/restore@v3
       id: ndk-cache-mac
       with:
diff --git a/.github/workflows/build-mac-50.yml b/.github/workflows/build-mac-50.yml
--- a/.github/workflows/build-mac-50.yml
+++ b/.github/workflows/build-mac-50.yml
@@ -6,9 +6,6 @@ on:
   workflow_dispatch:
 
 jobs:
-  build-ndk-mac:
-    uses: ./.github/workflows/build-ndk-mac.yml
-
   build-mac-50:
     runs-on: [ self-hosted, macOS, ARM64, m1-1317 ]
     needs: [ build-ndk-mac ]
@@ -22,11 +19,16 @@ jobs:
         echo $INWORLD_NDK_SHA
         echo "INWORLD_NDK_SHA=$INWORLD_NDK_SHA" >> $GITHUB_ENV
     - uses: actions/cache/restore@v3
-      id: ndk-cache
+      id: ndk-cache-mac
       with:
         path: InworldAI/inworld-ndk/build/Package
         key: ${{ runner.OS }}-ndk-cache-Mac-${{ env.INWORLD_NDK_SHA }}
         fail-on-cache-miss: true
+    - name: check-cache-success
+      if: steps.ndk-cache-mac.outputs.cache-hit != 'true'
+      run: |
+        echo "cache restore failed"
+        exit 1
     - name: Copy NDK
       run: |
         python3 "InworldAI/Source/ThirdParty/Inworld/dev-tools/ndk-util.py" --copy
diff --git a/.github/workflows/build-win-427.yml b/.github/workflows/build-win-427.yml
--- a/.github/workflows/build-win-427.yml
+++ b/.github/workflows/build-win-427.yml
@@ -6,9 +6,6 @@ on:
   workflow_dispatch:
 
 jobs:
-  build-ndk-win:
-    uses: ./.github/workflows/build-ndk-win.yml
-
   build-win-427:
     runs-on: [ self-hosted, Windows, X64, w10-1344 ]
     needs: [ build-ndk-win ]
@@ -27,6 +24,11 @@ jobs:
         path: InworldAI\inworld-ndk\build\Package
         key: ${{ runner.OS }}-ndk-cache-Win64-${{ env.INWORLD_NDK_SHA }}
         fail-on-cache-miss: true
+    - name: check-cache-success
+      if: steps.ndk-cache-win64.outputs.cache-hit != 'true'
+      run: |
+        echo "cache restore failed"
+        exit 1
     - name: Copy NDK
       run: |
           $pythonPath = (Get-Command python.exe).Source
